cocot/urls.py
from django.conf.urls import url
from django.contrib import admin
from monyong.views import task, check, check_progress
from monyong.views import check_log

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', task, name='home'),
    url(r'^check/(?P<task_id>\d+)$', check, name='check'),
    url(r'^check-progress/(?P<task_id>\d+)$', check_progress, name='check_progress'),
    url(r'^check-log/(?P<task_id>\d+)/(?P<pos>\d+)$', check_log, name='check_log')
]

monyong/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Task(models.Model):
    STATE = (
        ("S", "Start"),
        ("D", "Done"),
        ("X", "Cancel")
    )

    name = models.CharField(max_length=255)
    state = models.CharField(max_length=1, choices=STATE, default="S")
    progress = models.IntegerField(default=1)
    last_line_log = models.IntegerField(default=0)
    log = models.TextField(blank=True)

    def __unicode__(self):
        return self.name

monyong/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import threading
import json
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
from django.db.models import Value
from django.db.models.functions import Concat
from django.db.models import F

from multiprocessing import Process
from multiprocessing import active_children
from time import sleep
from uuid import uuid4
from .models import Task

def process(task):
    for a in range(20):    
        sleep(1)
        Task.objects.filter(id=task).update(
            last_line_log = F('last_line_log')+1,
            progress=a * 4,
            log=Concat('log', Value(str(a * 4) + "<br/>")))
    Task.objects.filter(id=task).update(state="D", progress=100)
    print task
    
def task(request):
    task = Task.objects.create(name=uuid4().hex, state="S")
    proc = Process(target=process, args=(task.id,), name=task.name)
    proc.daemon = True
    proc.start() 
    return render(request,"index.html", {"task": task})

def check(request, task_id):
    task = Task.objects.get(id=task_id)
    return render(request, "check.html", {"task": task})

def check_progress(request, task_id):
    ps_list = [p.name for p in active_children()]
    task = Task.objects.get(id=task_id)
    if task.name in ps_list:
        return HttpResponse(task.progress)
    else:
        if task.state != "D":
            Task.objects.filter(id=task_id).update(state="X",progress=100)
            return HttpResponse(100)
        else:
            return HttpResponse(100)
        
def check_log(request, task_id, pos):
    task = Task.objects.get(id=task_id)
    data = task.log.split("<br/>")
    del data[-1]
    resp = {
        "line": task.last_line_log,
        "result": "<br/>".join(data[int(pos):int(task.last_line_log)]) + "<br/>"
    }
    return JsonResponse(resp)

monyong/templates/check.html
<html>
    <head>
        <style>
            #myProgress {
                width: 100%;
                background-color: #e7e7e7;
            }
            #myBar {
                width: 1%;
                height: 30px;
                {% if task.state == "X" %}
                background-color: red;
                {% else %}
                background-color: green;
                {% endif %}
            }
        </style>
    </head>
    <body onload="move()">
        <h1>{{ task.get_state_display }}</h1>
        <div id="myProgress">
            <div id="myBar"></div>
        </div>
        <span id="log">{{ task.log|safe }}</span>
        <script>
            
            var last_line = {{ task.last_line_log|safe }};
            var xhttp = new XMLHttpRequest();
            
            function check_progress(){
                xhttp.open("GET", "/check-progress/{{ task.id }}", false);
                xhttp.send();
                return xhttp.responseText;
            }
            
            function check_log(){
                xhttp.open("GET", "/check-log/{{ task.id }}/"+last_line, false);
                xhttp.send();
                var myArr = JSON.parse(xhttp.responseText);
                return myArr;
            }
            
            function move() {
                var elem = document.getElementById("myBar");
                var log = document.getElementById("log");
                var width = 1;
                var id = setInterval(frame, 1000);
                function frame() {
                    if (width >= 100) {
                        clearInterval(id);
                    } else {
                        width = check_progress();
                        elem.style.width = check_progress() + '%';
                        var log_res = check_log();
                        if (log_res.result != "<br/>" ){
                            log.innerHTML += log_res.result;
                            last_line = log_res.line;
                        }
                        
                        
                    }
                }
            } 
        </script>
    </body>
</html>

monyong/templates/index.html
<html>
    <body>
        <a href="/check/{{ task.id }}">Check ME</a>
    </body>
</html>